# Generated by Django 3.2.7 on 2022-09-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='abstract',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
