# Generated by Django 4.1.1 on 2022-10-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='on_premises',
        ),
        migrations.RemoveField(
            model_name='collab',
            name='ownership',
        ),
        migrations.AddField(
            model_name='collab',
            name='model',
            field=models.CharField(choices=[('On premise', 'On premise'), ('Remote', 'Remote'), ('Field', 'Field'), ('Remote (Field)', 'Remote (Field)'), ('Others', 'Others')], max_length=14, null=True, verbose_name='Collaboration Model'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='abstract',
            field=models.TextField(max_length=2000, null=True, verbose_name='Reearch Description'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='collaborators_type',
            field=models.CharField(choices=[('Anyone', 'Anyone')], default='Anyone', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='collab',
            name='education',
            field=models.CharField(choices=[('0-2 years', '0-2 years'), ('3-5 years', '3-5 years'), ('6-10 years', '6-10 years'), ('10+ years', '10+ years')], max_length=20, null=True, verbose_name='Collaborators Research Experience'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='expertise_required',
            field=models.CharField(max_length=255, null=True, verbose_name="Collaborator's Expertise"),
        ),
        migrations.AlterField(
            model_name='collab',
            name='funding',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='type',
            field=models.CharField(choices=[('Researcher', 'Researcher'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Researcher', max_length=100, null=True),
        ),
    ]
