# Generated by Django 3.2.4 on 2022-10-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221013_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='type',
            field=models.CharField(choices=[('Researcher', 'Researcher'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Researcher', max_length=100, null=True),
        ),
    ]
