# Generated by Django 3.2.4 on 2022-10-10 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221010_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL, verbose_name='My Selection'),
        ),
    ]
