# Generated by Django 3.2.4 on 2022-08-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220731_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
