# Generated by Django 3.2.4 on 2022-10-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221015_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='collab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_folder', to='account.collab'),
        ),
    ]
