# Generated by Django 3.2.4 on 2022-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_researcher_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='users_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='affiliation_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Affiliation Address'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='affiliation_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Affiliation Name'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
