# Generated by Django 3.2.4 on 2022-10-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_collab_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='education',
            field=models.CharField(choices=[('0-2 years', '0-2 years'), ('3-5 years', '3-5 years'), ('6-10 years', '6-10 years')], max_length=15, null=True, verbose_name='Collaborators Research Experience'),
        ),
    ]
