# Generated by Django 3.2.4 on 2022-10-15 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_folder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_selected',
            field=models.ManyToManyField(blank=True, related_name='is_selected_folder', to=settings.AUTH_USER_MODEL),
        ),
    ]
