# Generated by Django 3.2.7 on 2022-09-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Stopped', 'Stopped')], default='Ongoing', max_length=9, null=True),
        ),
    ]
