# Generated by Django 3.2.4 on 2022-08-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='education',
            field=models.CharField(choices=[('Bachelor (BSc.)', 'Bachelor (BSc.)'), ('Masters (MSc.)', 'Masters (MSc.)'), ('Doctorate (PhD)', 'Doctorate (PhD)')], max_length=15, null=True),
        ),
    ]
