# Generated by Django 3.2.7 on 2022-09-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220918_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completed Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='stopped_date',
            field=models.DateField(blank=True, null=True, verbose_name='Stopped Date'),
        ),
    ]
