# Generated by Django 3.2.4 on 2022-10-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_collab_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='on_premises',
        ),
        migrations.AddField(
            model_name='collab',
            name='model',
            field=models.CharField(choices=[('On premise', 'On premise'), ('Remote', 'Remote'), ('Field', 'Field'), ('Remote (Field)', 'Remote (Field)'), ('Others', 'Others')], max_length=14, null=True, verbose_name='Collaboration Model'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='education',
            field=models.CharField(choices=[('0-2 years', '0-2 years'), ('3-5 years', '3-5 years'), ('6-10 years', '6-10 years'), ('10+ years', '10+ years')], max_length=10, null=True, verbose_name='Collaborators Research Experience'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='expertise_required',
            field=models.CharField(max_length=255, null=True, verbose_name="collaborator's Expertise"),
        ),
    ]
