# Generated by Django 3.2.4 on 2022-10-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20221011_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='ownership',
        ),
        migrations.AlterField(
            model_name='collab',
            name='expertise_required',
            field=models.CharField(max_length=255, null=True, verbose_name="Collaborator's Expertise"),
        ),
        migrations.AlterField(
            model_name='collab',
            name='funding',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
    ]
