# Generated by Django 3.2.7 on 2022-09-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220917_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('serial',)},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='collab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_chat', to='account.collab'),
        ),
        migrations.AddField(
            model_name='task',
            name='collab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_task', to='account.collab'),
        ),
    ]
