# Generated by Django 3.2.4 on 2022-08-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_collab_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='collaborators',
            field=models.CharField(max_length=255, null=True, verbose_name='Number of Collaborators'),
        ),
        migrations.AddField(
            model_name='collab',
            name='expertise_required',
            field=models.CharField(max_length=255, null=True, verbose_name='Expertise Required'),
        ),
        migrations.AddField(
            model_name='collab',
            name='field',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collab',
            name='funding',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collab',
            name='on_premises',
            field=models.CharField(max_length=255, null=True, verbose_name='On Premises'),
        ),
        migrations.AddField(
            model_name='collab',
            name='ownership',
            field=models.CharField(max_length=255, null=True, verbose_name='Research Ownership'),
        ),
        migrations.AddField(
            model_name='collab',
            name='proposed_timeline',
            field=models.CharField(max_length=255, null=True, verbose_name='Proposed Timeline'),
        ),
    ]
