# Generated by Django 3.2.7 on 2022-09-17 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220917_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_selected',
            field=models.ManyToManyField(blank=True, related_name='is_selected_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
