# Generated by Django 3.2.4 on 2022-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220816_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collab',
            old_name='collaborators',
            new_name='collaborators_no',
        ),
        migrations.AddField(
            model_name='collab',
            name='collaborators_type',
            field=models.CharField(choices=[('Anyone', 'Anyone'), ('Affiliation', 'Affiliation'), ('Select', 'Select')], default='Anyone', max_length=11, null=True),
        ),
    ]
