# Generated by Django 3.2.4 on 2022-10-17 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_collabdoc_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='funding',
            field=models.CharField(max_length=100, null=True, verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
