# Generated by Django 3.2.4 on 2022-08-16 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220816_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='collaborator',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
