# Generated by Django 3.2.4 on 2022-09-21 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_task_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assign'),
        ),
        migrations.AlterField(
            model_name='task',
            name='serial',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
