# Generated by Django 3.2.4 on 2022-10-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_folder_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_text',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
