# Generated by Django 3.2.4 on 2022-08-16 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_collab_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='collaborator',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Select'),
        ),
        migrations.AlterField(
            model_name='collab',
            name='collaborators_type',
            field=models.CharField(choices=[('Anyone', 'Anyone'), ('Affiliation', 'Affiliation')], default='Anyone', max_length=11, null=True),
        ),
    ]
