# Generated by Django 3.2.4 on 2022-09-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220921_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
