# Generated by Django 3.2.4 on 2022-10-19 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_task_text_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text_editor',
            field=models.ManyToManyField(blank=True, related_name='text_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
