# Generated by Django 3.2.4 on 2022-08-18 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220816_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collab',
            name='collaborator',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='My Selection'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='type',
            field=models.CharField(choices=[('Researcher/Collaborator', 'Researcher/Collaborator'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Researcher/Collaborator', max_length=23, null=True),
        ),
    ]
