# Generated by Django 3.2.4 on 2022-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_task_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='serial',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
