# Generated by Django 3.2.4 on 2022-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_task_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(default=False, max_length=5),
        ),
    ]
