# Generated by Django 3.2.4 on 2022-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_task_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='stopped_date',
        ),
        migrations.AddField(
            model_name='task',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
