# Generated by Django 3.2.4 on 2022-08-21 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220820_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='flag',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='collab',
            name='flag_counts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collab',
            name='interest',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='collab',
            name='interested_people',
            field=models.ManyToManyField(blank=True, related_name='interested_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collab',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL, verbose_name='My Selection'),
        ),
    ]
