# Generated by Django 3.2.4 on 2022-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20221020_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textupdate',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='textupdate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='textupdate',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='collabdoc',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='collabdoc',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='textupdate',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
