# Generated by Django 3.2.4 on 2022-09-21 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220921_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='task',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='task_poster'),
        ),
    ]
