# Generated by Django 3.2.4 on 2022-10-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20221020_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researcher',
            options={'ordering': ('first_name',), 'verbose_name': "Researcher's Profile", 'verbose_name_plural': "Researcher's Profiles"},
        ),
    ]
