# Generated by Django 3.2.4 on 2022-08-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220821_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collab',
            old_name='collaborator',
            new_name='collaborators',
        ),
    ]
