# Generated by Django 3.2.4 on 2022-10-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_researcher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='is_concluded',
            field=models.BooleanField(default=False, max_length=5),
        ),
    ]
