# Generated by Django 3.2.4 on 2022-09-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_task_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='serial',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
