# Generated by Django 3.2.4 on 2022-08-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='bell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.notification'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='bell_unreads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
