# Generated by Django 3.2.4 on 2022-10-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_collab_is_concluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
