# Generated by Django 3.2.4 on 2022-10-30 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_researcher_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='past_collaborators',
            field=models.ManyToManyField(blank=True, related_name='past_collaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
