# Generated by Django 3.2.4 on 2022-10-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_researcher_past_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='about',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
