# Generated by Django 3.2.4 on 2022-10-31 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_researcher_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='researcher_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researcher',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='researcher_followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
