# Generated by Django 3.2.4 on 2022-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20220827_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
    ]
