# Generated by Django 3.2.4 on 2022-11-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20221031_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='expertise',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Expertise/Techniques (List equipment you have expertise in using)'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='institution_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution Location'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution Name'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='specialzation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialization/Field'),
        ),
    ]
