# Generated by Django 3.2.4 on 2022-08-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20220827_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='flag',
        ),
    ]
