# Generated by Django 3.2.4 on 2022-08-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_collab_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_collab', to='account.flag'),
        ),
    ]
