# Generated by Django 3.2.4 on 2022-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20221102_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='award3',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Award'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='chapter',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Number of Book Chapters'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='google',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Scholar Profile Link'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='grants',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Number of Grants Awarded'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='patent_number',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Number of Patents'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='publication_number',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Number of Publications'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='textbooks',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Number of Textbooks Written (List Titles)'),
        ),
    ]
