# Generated by Django 3.2.4 on 2022-08-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_collab_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='locked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
