# Generated by Django 3.2.4 on 2022-11-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20221102_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='year_exit',
        ),
    ]
