# Generated by Django 3.2.4 on 2022-11-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_researcher_year_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
