# Generated by Django 3.2.4 on 2022-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_collab_locked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='type',
            field=models.CharField(choices=[('Researcher', 'Researcher'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Researcher/Collaborator', max_length=23, null=True),
        ),
    ]
