# Generated by Django 3.2.4 on 2022-11-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_researcher_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='employer_location',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='employer_name',
        ),
    ]
