# Generated by Django 3.2.4 on 2022-08-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_researcher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
