# Generated by Django 3.2.4 on 2022-11-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20221104_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='concluded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
