# Generated by Django 3.2.4 on 2022-11-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_collab_concluded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Preferred not to mention', 'Preferred not to mention')], max_length=24, null=True),
        ),
    ]
