# Generated by Django 3.2.4 on 2022-08-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_collab_accepted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='is_left',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='collab',
            name='is_removed',
            field=models.BooleanField(default=False, max_length=5),
        ),
    ]
