# Generated by Django 3.2.4 on 2022-11-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_researcher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Preferred not to mention', 'Preferred not to mention')], default='Preferred not to mention', max_length=24, null=True),
        ),
    ]
