# Generated by Django 3.2.4 on 2022-11-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_researcher_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='collaborators_type',
        ),
    ]
