# Generated by Django 3.2.7 on 2022-09-05 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20220830_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(upload_to='collab_documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reported', models.BooleanField(default=False, max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Stranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_username', models.EmailField(max_length=255, verbose_name='Enter institution email address')),
            ],
        ),
        migrations.RemoveField(
            model_name='researcherreport',
            name='collab',
        ),
        migrations.RemoveField(
            model_name='researcherreport',
            name='complainer',
        ),
        migrations.RemoveField(
            model_name='collab',
            name='collaborator_report',
        ),
        migrations.RemoveField(
            model_name='collab',
            name='researcher_report',
        ),
        migrations.AddField(
            model_name='collab',
            name='request_removed_people',
            field=models.ManyToManyField(blank=True, related_name='request_removed_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='affiliation_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='username',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.DeleteModel(
            name='CollaboratorReport',
        ),
        migrations.DeleteModel(
            name='ResearcherReport',
        ),
        migrations.AddField(
            model_name='report',
            name='collab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_collab', to='account.collab'),
        ),
        migrations.AddField(
            model_name='report',
            name='complainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_complainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collabdoc',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collab',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_report', to='account.report'),
        ),
    ]
