# Generated by Django 3.2.4 on 2022-11-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_remove_collab_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='funding',
            field=models.CharField(choices=[('On premise', 'On premise'), ('Remote', 'Remote'), ('Field', 'Field'), ('Remote (Field)', 'Remote (Field)'), ('Others', 'Others')], default='No funding', max_length=100, null=True, verbose_name='Funding'),
        ),
    ]
