# Generated by Django 3.2.7 on 2022-09-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20220905_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabdoc',
            name='is_selected',
            field=models.BooleanField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='collabdoc',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
