# Generated by Django 3.2.7 on 2022-09-05 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20220905_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabdoc',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='collabdoc',
            name='is_selected',
            field=models.ManyToManyField(blank=True, related_name='is_selected', to=settings.AUTH_USER_MODEL),
        ),
    ]
