# Generated by Django 3.2.4 on 2022-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_collab_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='user_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collab',
            name='funding',
            field=models.CharField(choices=[('Institution Internal Funding', 'Institution Internal Funding'), ('External Funding', 'External Funding'), ('No funding', 'No funding')], default='No funding', max_length=28, null=True, verbose_name='Funding'),
        ),
    ]
