# Generated by Django 3.2.7 on 2022-09-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_collabdoc_doc_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabdoc',
            name='collab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_collab_doc', to='account.collab'),
        ),
    ]
