# Generated by Django 3.2.4 on 2022-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_researcher_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='user_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
