# Generated by Django 3.2.7 on 2022-09-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_collabdoc_collab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collabdoc',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='collabdoc',
            name='document',
            field=models.FileField(upload_to='collab_documents/', verbose_name='File'),
        ),
    ]
