# Generated by Django 3.2.4 on 2022-11-09 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_researcher_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='task',
            name='text_editor',
            field=models.ManyToManyField(blank=True, related_name='text_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
