# Generated by Django 3.2.4 on 2022-09-28 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0016_task_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('aims', models.CharField(max_length=255, verbose_name='')),
                ('date_conducted', models.DateTimeField(blank=True, null=True, verbose_name='')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('setup', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('method', models.TextField(blank=True, null=True, verbose_name='')),
                ('result', models.TextField(blank=True, null=True, verbose_name='')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('collab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_research_note', to='account.collab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
