# Generated by Django 3.2.4 on 2022-10-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchnote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('serial',)},
        ),
    ]
