# Generated by Django 3.2.4 on 2022-10-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchnote', '0002_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='research_notes/', verbose_name='Attachment'),
        ),
    ]
