# Generated by Django 3.2.4 on 2022-09-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchnote', '0002_researchnote_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchnote',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='research_notes/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='researchnote',
            name='is_pinned',
            field=models.BooleanField(blank=True, default=False, max_length=5, null=True),
        ),
    ]
