# Generated by Django 3.2.4 on 2022-11-06 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_payment', models.DateField(null=True)),
                ('current_bill', models.CharField(max_length=13, null=True, verbose_name='Funding')),
                ('subscription_type', models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], max_length=7, null=True, verbose_name='Collaborators Research Experience')),
                ('subscription_ends', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
