# Generated by Django 3.2.4 on 2022-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20221107_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='current_bill',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], max_length=7, null=True),
        ),
    ]
