# Generated by Django 3.2.4 on 2022-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20221107_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
