# Generated by Django 3.2.4 on 2022-11-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20221107_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
