# Generated by Django 3.2.7 on 2022-09-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatnotification',
            name='collab',
        ),
    ]
