# Generated by Django 3.2.4 on 2022-09-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20220923_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('timestamp',)},
        ),
    ]
