# Generated by Django 3.2.4 on 2022-10-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20221020_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventavailable',
            name='available',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], default='Yes', max_length=5, null=True),
        ),
    ]
