# Generated by Django 3.2.14 on 2022-09-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_task_updated_by'),
        ('calendarapp', '0006_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_scheduler', to='account.collab'),
        ),
    ]
